Add inspection-batch workflow example
thoth-station/workflows pull request #1
Opened 2019-08-24 14:06 UTC by CermakM

This workflow submits a Job which creates `n` pod replicas and runs them in a sequence.

successCondition: `n` pods have finished successfully and are present in the cluster

The workflow simulates the scenario when we want to create a batch of inspections.

Signed-off-by: Marek Cermak <macermak@redhat.com>

new file:   examples/inspection-batch.yaml

2019-09-03 06:50 UTC, CermakM commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create examples of Argo Workflows.](https://trello.com/c/rbSVX7o4/730-create-examples-of-argo-workflows)

2019-09-05 07:45 UTC, goern requested changes

2019-09-05 07:45 UTC, goern commented on examples/inspection-batch.yaml
> +                image: alpine:latest
ubi8?!

2019-10-24 09:21 UTC, ghost commented
Build failed.

- [thoth-coala ](https://managesf.thoth-station.ninja/logs/1/1/f6de2447a7bc563194943547b7e9113412cd1035/check/thoth-coala/5849c53/) : FAILURE in 34s

2019-10-29 13:23 UTC, CermakM commented
recheck

2019-11-02 19:53 UTC, goern approved these changes

2019-11-02 19:54 UTC, merged