Inspection batch with failure
thoth-station/workflows pull request #2
Opened 2019-08-24 14:06 UTC by CermakM

2019-09-03 06:50 UTC, CermakM commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create examples of Argo Workflows.](https://trello.com/c/rbSVX7o4/730-create-examples-of-argo-workflows)

2019-09-05 07:46 UTC, goern requested changes

2019-09-05 07:46 UTC, goern commented on examples/inspection-batch-with-failure.yaml
> +                image: alpine:latest
ubi8!

2019-09-05 07:46 UTC, goern commented on examples/inspection-batch-with-failure.yaml
> +          parallelism: 0
missing \n

2019-10-29 13:11 UTC, goern reviewed
this needs some coala refinement yamllint config style?!

2019-10-29 13:24 UTC, CermakM commented
recheck

2019-11-02 19:53 UTC, goern approved these changes

2019-11-02 19:54 UTC, merged