Add inspection-batch-with-output-gathering example
thoth-station/workflows pull request #3
Opened 2019-09-03 06:11 UTC by CermakM

This workflow submits a Job which creates `n` pod replicas and runs them in a sequence.
Additionally, it mounts an artifact repository to store the resulting artifacts.

NOTE: The artifact repository has to be configured via ConfigMap, see
https://github.com/argoproj/argo/blob/master/ARTIFACT_REPO.md
or use the Argo ansible role: https://github.com/CermakM/ansible-role-argo-workflows

successCondition: `n` pods have finished successfully and are present in the cluster

The workflow simulates the scenario when we want to create a batch of inspections
and store the outputs to the artifact store.

Signed-off-by: Marek Cermak <macermak@redhat.com>

2019-09-03 06:50 UTC, CermakM commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create examples of Argo Workflows.](https://trello.com/c/rbSVX7o4/730-create-examples-of-argo-workflows)

2019-09-05 07:47 UTC, goern requested changes

2019-09-05 07:47 UTC, goern commented on examples/inspection-batch-with-output-gathering.yaml
> +                image: alpine:latest
ubi8!

2019-09-06 16:40 UTC, CermakM commented on examples/inspection-batch-with-output-gathering.yaml
> +                image: alpine:latest
docker?

2019-10-29 13:08 UTC, goern approved these changes

2019-10-29 13:10 UTC, goern commented
@CermakM this needs some love

2019-10-29 13:24 UTC, CermakM commented
recheck

2019-10-30 11:04 UTC, merged